#! /bin/sh
#  ____ _____
# |  _ \_   _|  Derek Taylor (DistroTube)
# | | | || |    http://www.youtube.com/c/DistroTube
# | |_| || |    http://www.gitlab.com/dwt1/
# |____/ |_|
#
# A customized bspwmrc for the bspwm window manager.
# https://github.com/baskerville/sxhkd
# https://github.com/baskerville/bspwm

#### AUTOSTART ####
killall sxhkd; sxhkd &
killall picom; picom -b --experimental-backends &
killall polybar; polybar ws &
polybar tray &


setxkbmap -model abnt2 -layout br -variant abnt2
feh --bg-fill Pictures/ocean.jpg
xsetroot -cursor_name left_ptr &
xset r rate 220 65

#### MONITORS ####
bspc monitor -d      term web code book campground music moon misc



#### BSPWM configuration ####
#bspc config border_radius                8

bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner




bspc config border_width 3
bspc config window_gap 10
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config swallow_first_click true


#### BSPWM coloring #

bspc config normal_border_color '#2A2525'
bspc config active_border_color '#494343'
bspc config focused_border_color '#494343'


#polybar hidden when fullscreen for vlc, youtube, mpv ...
#find out the name of your monitor with xrandr


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a brave-beta desktop='^2' state=tiled follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a 'Spotify' desktop='music' follow=on
bspc rule -a Zathura state=tiled
bspc rule -a inkscape state=floating




